INFO:root:Program started
INFO:root:Robot set up!
INFO:root:Odometry was started, PID: 27108:
INFO:root:Initial location: 0.2, 1.8, 0.0
WARNING:root:Traceback (most recent call last):
  File "/home/pi/oscar/main.py", line 57, in main
    actions.map.navigateMap(oscar, [0, 4], [4, 1])
  File "/home/pi/oscar/actions/map.py", line 36, in navigateMap
    print('Distancia a la pared del frente: {}\n Distancia a la pared de la izq: {}'.format(helpers.map.distance_front_wall(robot, map, size), helpers.map.distance_left_wall(robot, map, size)))
  File "/home/pi/oscar/helpers/map.py", line 212, in distance_left_wall
    rob_cell = pos2array(map_size, [robot.x.value, robot.y.value])
NameError: name 'robot' is not defined

WARNING:root:Abruptly stopped the robot!
INFO:root:Odometry was stopped
