INFO:root:MAIN: Program started
DEBUG:root:GENERATE_GRID: no hay que mezclar
INFO:root:ROBOT: Robot set up!
INFO:root:ROBOT: Odometry was started, PID: 11917:
INFO:root:MAIN: Initial location: 2.2, 2.6, -1.5707963267948966
INFO:root:*---------------------------------------------------------------------------*
INFO:root:Found the ball! Approaching...
INFO:root:Close enough to the ball, size is: 27.0629825592041
INFO:root:Centering the ball...
INFO:root:The ball's x position is: 75.09523010253906
INFO:root:Ball centered and ready to be catched!
INFO:root:The distance to be covered is: 0.18999999999999997 meters
INFO:root:BALL grab_ball: encoder value is 47
INFO:root:*---------------------------------------------------------------------------*
WARNING:root:Traceback (most recent call last):
  File "/home/pi/oscar/main.py", line 47, in main
    logging.debug('ENCODER VALUES: {} -- {}'.format(beg_val, end_val))
NameError: name 'beg_val' is not defined

WARNING:root:Abruptly stopped the robot!
INFO:root:Odometry was stopped
DEBUG:matplotlib.font_manager:findfont: Matching :family=sans-serif:style=normal:variant=normal:weight=normal:stretch=normal:size=10.0 to DejaVu Sans ('/home/pi/.local/lib/python3.5/site-packages/matplotlib/mpl-data/fonts/ttf/DejaVuSans.ttf') with score of 0.050000.
DEBUG:matplotlib.axes._base:update_title_pos
DEBUG:matplotlib.axes._base:update_title_pos
DEBUG:matplotlib.axes._base:update_title_pos
